export { default as Home} from './Home'
export { default as NotFound } from './NotFound'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Orders } from './Orders'
export { default as Cart } from './Cart'
export { default as Success } from './Success'